name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get -y install cmake libbluetooth-dev libsdl-dev freeglut3-dev
      - name: Dependencies (MacOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew update
          brew ls --versions cmake && brew upgrade cmake || brew install cmake
      - name: Dependencies (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install cmake
          Invoke-WebRequest https://buildbot.libsdl.org/sdl-builds/sdl-visualstudio-amd64/sdl-visualstudio-amd64-561.zip -O sdl.zip
          Expand-Archive -Path sdl.zip -DestinationPath ..
          Invoke-WebRequest https://www.transmissionzero.co.uk/files/software/development/GLUT/freeglut-MSVC.zip -O freeglut.zip
          Expand-Archive -Path freeglut.zip -DestinationPath ..
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

